In [2]:
%pip install --user pandas
import pandas as pd
df_docs = pd.read_csv("/scratch/aa5f25/datasets/yt8m/Queries_Genre.csv", sep=";")
df_docs

Requirement already satisfied: pandas in /iridisfs/home/aa5f25/.local/lib/python3.6/site-packages
Requirement already satisfied: numpy>=1.15.4 in /iridisfs/home/aa5f25/.local/lib/python3.6/site-packages (from pandas)
Requirement already satisfied: pytz>=2017.2 in /iridisfs/home/aa5f25/.local/lib/python3.6/site-packages (from pandas)
Requirement already satisfied: python-dateutil>=2.7.3 in /iridisfs/home/aa5f25/.local/lib/python3.6/site-packages (from pandas)
Requirement already satisfied: six>=1.5 in /iridisfs/home/aa5f25/.local/lib/python3.6/site-packages (from python-dateutil>=2.7.3->pandas)
Note: you may need to restart the kernel to use updated packages.

,id,video,audio,genre,publication_date,views,likes
0,deSR,"0.0616164207,-1.00776923,0.726923585,1.4439954...","0.770636,-0.360448927,-1.39757311,0.121328838,...",Nonprofits & Activism,2010-03-15T19:56:02-07:00,2608,8
1,9E9h,"0.410531461,0.747263491,-0.825599253,-0.709939...","-0.0263835788,-1.0880307,0.777590275,-0.682958...",Howto & Style,2012-07-11T03:25:20-07:00,38450,0
2,P6Cq,"-0.111586325,0.744629443,-0.799393654,-0.00393...","-0.454693735,-1.1063509,0.378908336,-1.0537979...",Autos & Vehicles,2015-02-07T21:09:24-08:00,46750,52
3,YYX3,"0.013093546,0.270139307,-0.858854175,0.1951588...","-0.660370529,-0.67108947,-0.120762661,0.868989...",Howto & Style,2012-11-09T13:55:48-08:00,11407,26
4,qeE7,"-0.484161347,0.386270016,1.73121119,-0.1305927...","1.2543484,-0.031926062,0.421093553,-0.20060579...",Music,2013-08-02T13:46:50-07:00,20879,267
...,...,...,...,...,...,...,...
1495,NHsY,"-0.0219669119,0.0346507356,-0.343290448,1.5682...","-1.65493262,1.7869792,-0.953952193,1.98489583,...",Sports,2014-03-12T05:00:03-07:00,2336,3
1496,hffa,"-1.93749464,-0.483324766,-1.37655354,0.4070281...","0.0180608667,-1.12264502,-0.393180966,-0.07987...",Gaming,2013-09-20T20:01:08-07:00,28455,141
1497,wDfq,"0.690078318,0.77443558,-0.22730732,-0.05580405...","-0.106087282,-0.155150458,-0.361773551,0.80441...",People & Blogs,2014-07-19T11:19:51-07:00,4426,20
1498,CxCu,"0.362154245,-1.2555629,-1.17699146,1.42959118,...","1.24919903,-0.553111851,-0.9114452,-0.00920430...",Science & Technology,2007-12-17T22:03:49-08:00,9041,9
1499,ALGa,"0.450443745,-0.187759921,-0.251643538,1.184662...","-0.246709958,-0.306419,-0.483395606,0.86005789...",Sports,2012-11-23T02:39:04-08:00,2750,14

In [4]:

df_queries= pd.read_csv("/scratch/aa5f25/datasets/paper/paper_queries_with_attributes.csv", sep=";")
df_queries

,embedding,rand_int,query_attribute,query_attribute3,query_attribute5
0,"0.18394100666046143,-0.0625929981470108,-0.108...",11,1,3,5
1,"0.20332999527454376,-0.09437700361013412,-0.10...",2,1,3,5
2,"0.11066299676895142,-0.044043999165296555,-0.0...",1,1,3,5
3,"0.24615100026130676,-0.10814200341701508,-0.00...",12,1,3,5
4,"0.32651498913764954,-0.16267600655555725,-0.10...",5,1,3,5
...,...,...,...,...,...
9995,"0.17453999817371368,-0.16027599573135376,-0.05...",7,1,3,5
9996,"0.16341200470924377,-0.13118599355220795,-0.01...",2,1,3,5
9997,"0.1755719929933548,-0.21993699669837952,-0.085...",4,1,3,5
9998,"0.17396600544452667,-0.06954299658536911,-0.08...",8,1,3,5
9999,"0.2477409988641739,-0.11929599940776825,-0.126...",11,1,3,5

In [23]:
# Source - https://stackoverflow.com/a/18145399
# Posted by LondonRob, modified by community. See post 'Timeline' for change history
# Retrieved 2026-03-03, License - CC BY-SA 4.0

df_docs= df_docs.drop('query_label', axis=1)

In [ ]:
df_docs

                                                 embedding  rand_int
0        0.2629320025444031,-0.22875100374221802,-0.104...        11
1        0.30364999175071716,-0.19963900744915009,-0.09...         2
2        0.2946319878101349,-0.25989100337028503,-0.178...         1
3        0.26827698945999146,-0.10750100016593933,-0.13...        12
4        0.27969199419021606,-0.15651899576187134,-0.18...         5
...                                                    ...       ...
2029992  0.21286900341510773,-0.10654100030660629,-0.08...        12
2029993  0.2582069933414459,-0.1930209994316101,-0.1495...         8
2029994  0.22436200082302094,-0.15109199285507202,-0.18...         3
2029995  0.23794099688529968,-0.07481200248003006,-0.08...         8
2029996  0.17699599266052246,-0.21894900500774384,-0.11...         7

[2029997 rows x 2 columns]

In [42]:
df_queries = pd.read_csv("/scratch/aa5f25/datasets/paper/paper_queries_with_attributes.csv", sep=";")
df_queries

,embedding,rand_int,query_attribute,query_attribute3,query_attribute5
0,"0.18394100666046143,-0.0625929981470108,-0.108...",11,1,3,5
1,"0.20332999527454376,-0.09437700361013412,-0.10...",2,1,3,5
2,"0.11066299676895142,-0.044043999165296555,-0.0...",1,1,3,5
3,"0.24615100026130676,-0.10814200341701508,-0.00...",12,1,3,5
4,"0.32651498913764954,-0.16267600655555725,-0.10...",5,1,3,5
...,...,...,...,...,...
9995,"0.17453999817371368,-0.16027599573135376,-0.05...",7,1,3,5
9996,"0.16341200470924377,-0.13118599355220795,-0.01...",2,1,3,5
9997,"0.1755719929933548,-0.21993699669837952,-0.085...",4,1,3,5
9998,"0.17396600544452667,-0.06954299658536911,-0.08...",8,1,3,5
9999,"0.2477409988641739,-0.11929599940776825,-0.126...",11,1,3,5

In [25]:
df_queries= df_queries.drop('query_label', axis=1)

In [26]:
df_queries

                                              embedding  rand_int
0     0.18394100666046143,-0.0625929981470108,-0.108...        11
1     0.20332999527454376,-0.09437700361013412,-0.10...         2
2     0.11066299676895142,-0.044043999165296555,-0.0...         1
3     0.24615100026130676,-0.10814200341701508,-0.00...        12
4     0.32651498913764954,-0.16267600655555725,-0.10...         5
...                                                 ...       ...
9995  0.17453999817371368,-0.16027599573135376,-0.05...         7
9996  0.16341200470924377,-0.13118599355220795,-0.01...         2
9997  0.1755719929933548,-0.21993699669837952,-0.085...         4
9998  0.17396600544452667,-0.06954299658536911,-0.08...         8
9999  0.2477409988641739,-0.11929599940776825,-0.126...        11

[10000 rows x 2 columns]

In [12]:
df_docs

                                                 embedding  rand_int
0        0.2629320025444031,-0.22875100374221802,-0.104...        11
1        0.30364999175071716,-0.19963900744915009,-0.09...         2
2        0.2946319878101349,-0.25989100337028503,-0.178...         1
3        0.26827698945999146,-0.10750100016593933,-0.13...        12
4        0.27969199419021606,-0.15651899576187134,-0.18...         5
...                                                    ...       ...
2029992  0.21286900341510773,-0.10654100030660629,-0.08...        12
2029993  0.2582069933414459,-0.1930209994316101,-0.1495...         8
2029994  0.22436200082302094,-0.15109199285507202,-0.18...         3
2029995  0.23794099688529968,-0.07481200248003006,-0.08...         8
2029996  0.17699599266052246,-0.21894900500774384,-0.11...         7

[2029997 rows x 2 columns]

In [40]:
df_queries["query_attribute5"] = "5"

In [39]:
df_queries

,embedding,rand_int,query_attribute,query_attribute3
0,"0.18394100666046143,-0.0625929981470108,-0.108...",11,1,3
1,"0.20332999527454376,-0.09437700361013412,-0.10...",2,1,3
2,"0.11066299676895142,-0.044043999165296555,-0.0...",1,1,3
3,"0.24615100026130676,-0.10814200341701508,-0.00...",12,1,3
4,"0.32651498913764954,-0.16267600655555725,-0.10...",5,1,3
...,...,...,...,...
9995,"0.17453999817371368,-0.16027599573135376,-0.05...",7,1,3
9996,"0.16341200470924377,-0.13118599355220795,-0.01...",2,1,3
9997,"0.1755719929933548,-0.21993699669837952,-0.085...",4,1,3
9998,"0.17396600544452667,-0.06954299658536911,-0.08...",8,1,3
9999,"0.2477409988641739,-0.11929599940776825,-0.126...",11,1,3

In [29]:
import pandas as pd
import numpy as np

# Number of rows
N = len(df_docs)

# New column
df_docs["attribute"] = 0  # initialize

# Shuffle indices randomly
indices = np.arange(N)
np.random.shuffle(indices)

# Compute counts
n1 = int(0.10 * N)
n3 = int(0.30 * N)
n5 = int(0.50 * N)
n_rest = N - (n1 + n3 + n5)  # should be 10%

# Assign values
df_docs.loc[indices[:n1], "attribute"] = 1
df_docs.loc[indices[n1:n1+n3], "attribute"] = 3
df_docs.loc[indices[n1+n3:n1+n3+n5], "attribute"] = 5
df_docs.loc[indices[n1+n3+n5:], "attribute"] = -1

# Check distribution
df_docs

,embedding,rand_int,attribute
0,"0.2629320025444031,-0.22875100374221802,-0.104...",11,5
1,"0.30364999175071716,-0.19963900744915009,-0.09...",2,5
2,"0.2946319878101349,-0.25989100337028503,-0.178...",1,3
3,"0.26827698945999146,-0.10750100016593933,-0.13...",12,5
4,"0.27969199419021606,-0.15651899576187134,-0.18...",5,5
...,...,...,...
2029992,"0.21286900341510773,-0.10654100030660629,-0.08...",12,3
2029993,"0.2582069933414459,-0.1930209994316101,-0.1495...",8,5
2029994,"0.22436200082302094,-0.15109199285507202,-0.18...",3,-1
2029995,"0.23794099688529968,-0.07481200248003006,-0.08...",8,5
2029996,"0.17699599266052246,-0.21894900500774384,-0.11...",7,3

In [30]:
# Count and percentage
percentages = df_docs["attribute"].value_counts(normalize=True) * 100
print(percentages)

 5    49.999975
 3    29.999995
-1    10.000064
 1     9.999966
Name: attribute, dtype: float64

In [41]:
df_queries.to_csv("/scratch/aa5f25/datasets/paper/paper_queries_with_attributes.csv", index=False, sep=";")

In [21]:
import pandas as pd
import numpy as np
import time
from multiprocessing import Pool, cpu_count

# -----------------------------
# CONFIGURATION
# -----------------------------
N = len(df_docs)            # Number of documents
selectivity = 0.10          # 10%
target = int(selectivity * N)
batch_size = 50             # queries per batch
output_file = "doc_query_attr_2000.csv"

df_docs = df_docs.reset_index(drop=True)
# Only first 2000 queries
queries = df_queries["query_attribute"].astype(str).values[:2000]

# -----------------------------
# HELPER FUNCTION FOR PARALLEL
# -----------------------------
def process_query(q):
    """Assign a single query to random documents"""
    chosen = np.random.choice(N, size=target, replace=False)
    return [(idx, q) for idx in chosen]

# -----------------------------
# MAIN PARALLEL BATCH LOOP
# -----------------------------
start_time = time.time()
first_write = True

for batch_start in range(0, len(queries), batch_size):
    batch_end = min(batch_start + batch_size, len(queries))
    batch_queries = queries[batch_start:batch_end]

    # Parallel processing
    with Pool(processes=cpu_count()) as pool:
        results = pool.map(process_query, batch_queries)

    # Flatten results into doc -> list of queries
    doc_attr = [[] for _ in range(N)]
    for res in results:
        for idx, q in res:
            doc_attr[idx].append(q)

    # Convert lists to comma-separated strings
    doc_attr_str = [",".join(x) for x in doc_attr]

    # Save batch to CSV
    df_out = pd.DataFrame({
        "doc_id": df_docs.index,
        "query_attribute": doc_attr_str
    })
    df_out.to_csv(output_file, mode="w" if first_write else "a",
                  index=False, header=first_write)
    first_write = False

    # Progress display
    elapsed = time.time() - start_time
    processed = batch_end
    percent = (processed / len(queries)) * 100
    print(f"Processed {processed}/{len(queries)} queries "
          f"({percent:.2f}%) | Time elapsed: {elapsed/60:.2f} min")

print("✅ Finished writing comma-separated attributes for first 2000 queries.")

Process ForkPoolWorker-1864:
Process ForkPoolWorker-1857:
Process ForkPoolWorker-1863:
Process ForkPoolWorker-1858:
Process ForkPoolWorker-1859:
Process ForkPoolWorker-1862:
Process ForkPoolWorker-1860:
Process ForkPoolWorker-1861:
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)

KeyboardInterrupt:

  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/usr/lib64/python3.6/multiprocessing/queues.py", line 334, in get
    with self._rlock:
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/usr/lib64/python3.6/multiprocessing/queues.py", line 334, in get
    with self._rlock:
  File "/usr/lib64/python3.6/multiprocessing/queues.py", line 334, in get
    with self._rlock:
  File "/usr/lib64/python3.6/multiprocessing/queues.py", line 334, in get
    with self._rlock:
  File "/usr/lib64/python3.6/multiprocessing/queues.py", line 334, in get
    with self._rlock:
  File "/usr/lib64/python3.6/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/usr/lib64/python3.6/multiprocessing/queues.py", line 334, in get
    with self._rlock:
  File "/usr/lib64/python3.6/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/usr/lib64/python3.6/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/usr/lib64/python3.6/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/usr/lib64/python3.6/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
  File "/usr/lib64/python3.6/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
KeyboardInterrupt
KeyboardInterrupt
KeyboardInterrupt
KeyboardInterrupt

Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/usr/lib64/python3.6/multiprocessing/queues.py", line 335, in get
    res = self._reader.recv_bytes()
  File "/usr/lib64/python3.6/multiprocessing/queues.py", line 334, in get
    with self._rlock:
  File "/usr/lib64/python3.6/multiprocessing/connection.py", line 220, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib64/python3.6/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/usr/lib64/python3.6/multiprocessing/connection.py", line 411, in _recv_bytes
    buf = self._recv(4)
KeyboardInterrupt
  File "/usr/lib64/python3.6/multiprocessing/connection.py", line 383, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt

In [26]:
df_queries1

                                             embedding  correlation
0    -0.3205789,0.06644345,0.22195277,-0.13523898,-...            0
1    -0.2833061,-0.13634399,0.38554284,-0.28529945,...            1
2    0.03552235,0.31721422,0.2561202,0.060554873,0....            2
3    0.1314554,0.31659058,0.0035175257,-0.17587781,...            3
4    -0.36439136,0.07383215,0.3017879,-0.2734844,0....            4
..                                                 ...          ...
995  0.15833698,-0.03161161,0.71027946,0.032480977,...          995
996  0.027496073,-0.10356202,0.76896113,-0.19816184...          996
997  -0.10130168,-0.08833368,-0.10891157,-0.2263839...          997
998  0.0006294999,-0.3083132,0.61100656,-0.12058302...          998
999  0.00072121306,-0.02960684,0.40997794,-0.037810...          999

[1000 rows x 2 columns]

In [17]:
df2 = df[["embedding", "correlation_files"]]

In [18]:
df2

                                                embedding correlation_files
0       -0.3425868,0.32548454,0.4870531,-0.37503994,-0...                -1
1       -0.11744792,-0.19202681,0.50087184,-0.16649805...                -1
2       -0.19148643,0.0009214283,0.34294525,-0.3131651...                -1
3       -0.27164686,0.07948127,0.39479753,-0.5501128,-...                -1
4       -0.1501147,0.26418093,0.4900402,-0.41568285,-0...                -1
...                                                   ...               ...
813481  -0.004253374,-0.05755319,0.42041805,-0.3706104...                -1
813482  -0.19087975,-0.18493585,0.6684668,-0.16273195,...                -1
813483  -0.0339704,-0.059509445,0.57890916,-0.52386916...                -1
813484  -0.10159028,-0.17919351,0.53581035,-0.3646105,...                -1
813485  -0.080517,0.14794855,0.5342876,-0.3118318,-0.0...                -1

[813486 rows x 2 columns]

In [28]:
import numpy as np
df["value_20"] = np.where(
    np.random.rand(len(df)) < 0.2,
    1,
    np.random.randint(2, 13, size=len(df))
)

In [29]:
df

,embedding,rand_int,value_90,value_80,value_60,value_40,value_20
0,"0.18394100666046143,-0.0625929981470108,-0.108...",11,1,7,1,1,4
1,"0.20332999527454376,-0.09437700361013412,-0.10...",2,1,1,1,12,7
2,"0.11066299676895142,-0.044043999165296555,-0.0...",1,1,1,1,4,6
3,"0.24615100026130676,-0.10814200341701508,-0.00...",12,1,1,1,1,8
4,"0.32651498913764954,-0.16267600655555725,-0.10...",5,1,1,7,1,5
...,...,...,...,...,...,...,...
9995,"0.17453999817371368,-0.16027599573135376,-0.05...",7,1,1,1,1,12
9996,"0.16341200470924377,-0.13118599355220795,-0.01...",2,1,1,1,2,5
9997,"0.1755719929933548,-0.21993699669837952,-0.085...",4,1,1,1,1,11
9998,"0.17396600544452667,-0.06954299658536911,-0.08...",8,8,9,2,1,1
9999,"0.2477409988641739,-0.11929599940776825,-0.126...",11,1,3,5,8,11

In [4]:
import re

text = """
Search Time for efSearch=20 => Total Queries: 1500, Total Time: 2.397s, QPS: 625.782
Search Time for efSearch=40 => Total Queries: 1500, Total Time: 2.838s, QPS: 528.541
Search Time for efSearch=80 => Total Queries: 1500, Total Time: 3.576s, QPS: 419.463
Search Time for efSearch=100 => Total Queries: 1500, Total Time: 4.127s, QPS: 363.46
Search Time for efSearch=200 => Total Queries: 1500, Total Time: 5.87s, QPS: 255.537
Search Time for efSearch=300 => Total Queries: 1500, Total Time: 7.482s, QPS: 200.481
Search Time for efSearch=500 => Total Queries: 1500, Total Time: 10.948s, QPS: 137.011
Search Time for efSearch=800 => Total Queries: 1500, Total Time: 14.417s, QPS: 104.044
Search Time for efSearch=1000 => Total Queries: 1500, Total Time: 17.984s, QPS: 83.4075
Search Time for efSearch=1200 => Total Queries: 1500, Total Time: 20.325s, QPS: 73.8007
Search Time for efSearch=1500 => Total Queries: 1500, Total Time: 24.86s, QPS: 60.3379



"""

# Extract QPS values using regex
qps_values = re.findall(r"QPS:\s*([\d\.]+)", text)

# Convert strings to float
qps_array = [float(q) for q in qps_values]

print(qps_array)

[625.782, 528.541, 419.463, 363.46, 255.537, 200.481, 137.011, 104.044, 83.4075, 73.8007, 60.3379]

In [34]:
df["value_80"].value_counts(normalize=True) * 100

1     79.21
3      2.11
5      2.03
10     1.98
11     1.97
7      1.87
12     1.87
8      1.86
9      1.85
4      1.80
2      1.74
6      1.71
Name: value_80, dtype: float64

In [3]:
numbers =[1646.36, 1711.45, 1565.44, 1484.56, 1354.46, 1240.85, 1050.75, 904.486, 805.477, 673.537, 532.34]

sorted_numbers = sorted(numbers, reverse=True)

print(sorted_numbers)

[1711.45, 1646.36, 1565.44, 1484.56, 1354.46, 1240.85, 1050.75, 904.486, 805.477, 673.537, 532.34]

In [ ]:
column_name = "random_value"

# 1️⃣ Count frequency of each unique value
freq_counts = df[column_name].value_counts().sort_index()
print("Counts:")
print(freq_counts)

# 2️⃣ Convert to percentage
freq_percent = df[column_name].value_counts(normalize=True).sort_index() * 100
print("\nPercentages:")
print(freq_percent)

# 3️⃣ Combine into a single DataFrame for easy view / export
verification_df = pd.DataFrame({
    "random_value": freq_counts.index,
    "count": freq_counts.values,
    "percentage": freq_percent.values
})

print("\nVerification table:")
print(verification_df)

In [21]:
import random
from collections import Counter
import pandas as pd

TOTAL = 10000
data = []

# Fixed counts for 1–4
data.extend([1] * 2950)
data.extend([2] * 1972)
data.extend([3] * 1479)
data.extend([4] * 986)

# Remaining rows for 5–12
remaining = TOTAL - len(data)  # 2,613
values_5_to_12 = list(range(5, 13))  # 8 numbers
per_value = remaining // len(values_5_to_12)  # 326
extra = remaining % len(values_5_to_12)       # 5 leftover rows

for i, v in enumerate(values_5_to_12):
    count = per_value + (1 if i < extra else 0)  # distribute leftover
    data.extend([v] * count)

# Shuffle
random.shuffle(data)

# Load into pandas
df_random_items = pd.DataFrame(data, columns=["random_value"])

# Verification
print("Total rows:", len(df_random_items))  # Should be 10,000
print(Counter(df_random_items["random_value"]))

Total rows: 10000
Counter({1: 2950, 2: 1972, 3: 1479, 4: 986, 8: 327, 5: 327, 9: 327, 6: 327, 7: 327, 11: 326, 12: 326, 10: 326})

In [22]:
df_random_items

      random_value
0                2
1                2
2                3
3                4
4               11
...            ...
9995             4
9996             6
9997             2
9998             2
9999             7

[10000 rows x 1 columns]

In [23]:
assert len(df) == len(df_random_items), "DataFrames must have the same length!"

# Add the column
df["random_value"] = df_random_items["random_value"]
df

,embedding,rand_int,random_value
0,"0.18394100666046143,-0.0625929981470108,-0.108...",11,2
1,"0.20332999527454376,-0.09437700361013412,-0.10...",2,2
2,"0.11066299676895142,-0.044043999165296555,-0.0...",1,3
3,"0.24615100026130676,-0.10814200341701508,-0.00...",12,4
4,"0.32651498913764954,-0.16267600655555725,-0.10...",5,11
...,...,...,...
9995,"0.17453999817371368,-0.16027599573135376,-0.05...",7,4
9996,"0.16341200470924377,-0.13118599355220795,-0.01...",2,6
9997,"0.1755719929933548,-0.21993699669837952,-0.085...",4,2
9998,"0.17396600544452667,-0.06954299658536911,-0.08...",8,2
9999,"0.2477409988641739,-0.11929599940776825,-0.126...",11,7

In [24]:
df.to_csv("/home/aa5f25/Dataset/data/hnsw/paper/paper_queries.csv", index=False, sep=";")

In [3]:
import pandas as pd
df = pd.read_csv("/scratch/aa5f25/datasets/paper/paper_docs.csv", sep=";")
df

                                                 embedding  rand_int
0        0.2629320025444031,-0.22875100374221802,-0.104...        11
1        0.30364999175071716,-0.19963900744915009,-0.09...         2
2        0.2946319878101349,-0.25989100337028503,-0.178...         1
3        0.26827698945999146,-0.10750100016593933,-0.13...        12
4        0.27969199419021606,-0.15651899576187134,-0.18...         5
...                                                    ...       ...
2029992  0.21286900341510773,-0.10654100030660629,-0.08...        12
2029993  0.2582069933414459,-0.1930209994316101,-0.1495...         8
2029994  0.22436200082302094,-0.15109199285507202,-0.18...         3
2029995  0.23794099688529968,-0.07481200248003006,-0.08...         8
2029996  0.17699599266052246,-0.21894900500774384,-0.11...         7

[2029997 rows x 2 columns]

In [30]:
import os
import pandas as pd

# Example: load your dataframe
# df = pd.read_csv("your_dataset.csv")
# Make sure index matches those numbers
# df.index = df.index.astype(int)
df = pd.read_csv("/scratch/aa5f25/datasets/TripClick/documents_full.csv", sep=";")


folder_path = "/scratch/aa5f25/datasets/TripClick/Corelation"  # <-- your folder path

# Create empty column
df["correlation_files"] = ""

for file in os.listdir(folder_path):
    if not file.endswith(".csv"):
        continue

    file_path = os.path.join(folder_path, file)

    # Read the single-line file
    with open(file_path, "r") as f:
        line = f.readline().strip()

    if not line:
        continue

    # Split left and right
    key, idx_string = line.split(";")

    # Convert index positions to list of integers
    indices = list(map(int, idx_string.split(",")))

    # Keep only valid indices (avoid crash if bad index exists)
    valid_indices = [i for i in indices if i in df.index]

    # Update dataframe
    for idx in valid_indices:
        if df.at[idx, "correlation_files"] == "":
            df.at[idx, "correlation_files"] = key
        else:
            df.at[idx, "correlation_files"] += f",{key}"

print("Done processing all files.")

Done processing all files.

In [31]:
df

,DateCreated,ClinicalAreas,embedding,correlation_files
0,2020-02-23,Gastroenterology,"-0.3425868,0.32548454,0.4870531,-0.37503994,-0...",
1,2020-02-23,Gastroenterology,"-0.11744792,-0.19202681,0.50087184,-0.16649805...",
2,2020-02-23,Gastroenterology,"-0.19148643,0.0009214283,0.34294525,-0.3131651...",
3,2020-02-23,Gastroenterology,"-0.27164686,0.07948127,0.39479753,-0.5501128,-...",
4,2020-02-23,Gastroenterology,"-0.1501147,0.26418093,0.4900402,-0.41568285,-0...",
...,...,...,...,...
813481,2020-09-29,Geriatrics,"-0.004253374,-0.05755319,0.42041805,-0.3706104...",
813482,2020-09-29,Geriatrics,"-0.19087975,-0.18493585,0.6684668,-0.16273195,...",
813483,2020-09-29,Geriatrics,"-0.0339704,-0.059509445,0.57890916,-0.52386916...",
813484,2020-09-29,Geriatrics,"-0.10159028,-0.17919351,0.53581035,-0.3646105,...",
813485,2020-09-29,Geriatrics,"-0.080517,0.14794855,0.5342876,-0.3118318,-0.0...",

In [32]:
df1= df[['embedding', 'correlation_files']]

In [33]:
df1

                                                embedding correlation_files
0       -0.3425868,0.32548454,0.4870531,-0.37503994,-0...
1       -0.11744792,-0.19202681,0.50087184,-0.16649805...
2       -0.19148643,0.0009214283,0.34294525,-0.3131651...
3       -0.27164686,0.07948127,0.39479753,-0.5501128,-...
4       -0.1501147,0.26418093,0.4900402,-0.41568285,-0...
...                                                   ...               ...
813481  -0.004253374,-0.05755319,0.42041805,-0.3706104...
813482  -0.19087975,-0.18493585,0.6684668,-0.16273195,...
813483  -0.0339704,-0.059509445,0.57890916,-0.52386916...
813484  -0.10159028,-0.17919351,0.53581035,-0.3646105,...
813485  -0.080517,0.14794855,0.5342876,-0.3118318,-0.0...

[813486 rows x 2 columns]

In [8]:
print(df1.loc[710264])

embedding            0.076131254,0.32869706,-0.26396635,0.46133634,...
correlation_files    537,949,743,213,592,77,395,428,870,174,800,78,...
Name: 710264, dtype: object

In [10]:
df1["correlation_files"] = df1["correlation_files"].fillna(-1)

/home/aa5f25/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
df1.to_csv("/scratch/aa5f25/datasets/TripClick/TripClick_queries_with_correlation.csv", index=False, sep=";")

In [1]:
import pandas as pd
df = pd.read_csv("/scratch/aa5f25/datasets/yt8m/Queries_for_conjunctive_disjunctive.csv", sep=";")
df

,id,video,audio,start_range,end_range,genre
0,deSR,"0.0616164207,-1.00776923,0.726923585,1.4439954...","0.770636,-0.360448927,-1.39757311,0.121328838,...",1349,2608,Nonprofits & Activism
1,9E9h,"0.410531461,0.747263491,-0.825599253,-0.709939...","-0.0263835788,-1.0880307,0.777590275,-0.682958...",4464,38450,Howto & Style
2,P6Cq,"-0.111586325,0.744629443,-0.799393654,-0.00393...","-0.454693735,-1.1063509,0.378908336,-1.0537979...",11310,46750,Autos & Vehicles
3,YYX3,"0.013093546,0.270139307,-0.858854175,0.1951588...","-0.660370529,-0.67108947,-0.120762661,0.868989...",11407,32454,Howto & Style
4,qeE7,"-0.484161347,0.386270016,1.73121119,-0.1305927...","1.2543484,-0.031926062,0.421093553,-0.20060579...",20879,20977,Music
...,...,...,...,...,...,...
1495,NHsY,"-0.0219669119,0.0346507356,-0.343290448,1.5682...","-1.65493262,1.7869792,-0.953952193,1.98489583,...",1288,2336,Sports
1496,hffa,"-1.93749464,-0.483324766,-1.37655354,0.4070281...","0.0180608667,-1.12264502,-0.393180966,-0.07987...",7821,28455,Gaming
1497,wDfq,"0.690078318,0.77443558,-0.22730732,-0.05580405...","-0.106087282,-0.155150458,-0.361773551,0.80441...",3584,4426,People & Blogs
1498,CxCu,"0.362154245,-1.2555629,-1.17699146,1.42959118,...","1.24919903,-0.553111851,-0.9114452,-0.00920430...",9041,56063,Science & Technology
1499,ALGa,"0.450443745,-0.187759921,-0.251643538,1.184662...","-0.246709958,-0.306419,-0.483395606,0.86005789...",1408,2750,Sports